# Generated by Django 5.0.1 on 2024-01-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_images',
            new_name='doc_image',
        ),
    ]
